wsgi/openshift/administration/urls.py
from django.conf.urls import patterns, url
from administration import views
from django.contrib.auth.decorators import login_required, user_passes_test

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^contact/', views.contact, name='contact'), 
	url(r'^about/', views.about, name='about'),    
	url(r'^blog/(?P<blog_id>\d+)/$', views.blog, name='blog'),
	url(r'^signup/$', views.signup, name='signup'),
	url(r'^login/$', views.login_user, name='login'),
	# url(r'^login/(?P<same_site>\w+)/$', views.login_user, name='login'),
	url(r'^profile/$', login_required(views.profile), name='profile'),
	url(r'^profile/changepassword/$', login_required(views.change_password), name='changepassword'),
	url(r'^asdjsaidio21u312/sendemail/$', login_required(views.sendEmailAimbot), name='sendemailaimbot'),
	url(r'^adlsakd9012312123/activatepremium/$', login_required(views.activatePremium), name='activatepremium'),
	url(r'^ddj9pqjdwq09dj90ad/showuserprofile/(?P<pk>\d+)/$', login_required(views.showUserProfile), name='showuserprofile'),
	url(r'^asdasdj90je9032je903je932je029ej2903je9032je9032e/premiums/$', login_required(views.PremiumListJSON.as_view()), name='premiums'),
	url(r'^cnaisncoasdaoisdjddj9j0021312dapajdznmnzadi0123jd/payments/$', login_required(views.PaymentListJSON.as_view()), name='payments'),
	url(r'^logout/$', views.logout_user, name='logout'),
	# url(r'^setusername/(?P<user_url>\w+)/$', views.setUsername, name='setUsername'),
	url(r'^development/$', views.development, name='development'),
	url(r'^development/sendvoucher/$', views.sendVoucher, name='sendvoucher'),
	# url(r'^development/payment/$', views.view_that_asks_for_money, name='payment'),
	url(r'^development/bots/$', views.bots, name='bots'),
	url(r'^development/events/$', views.events, name='events'),	
	url(r'^development/confirmpurchase/$', login_required(views.confirm_purchase), name='confirm_purchase'),	
	# url(r'^development/no_authorized/$', views.confirm_purchase, name='confirmpurchase'),
	url(r'^development/bots/(?P<bot>\w+)/$', views.specificBot, name='specificBot'),
	url(r'^conditions/$', views.conditions, name='conditions'),
)

wsgi/openshift/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

handler404 = 'mysite.views.handler404'


urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'openshift.views.home', name='home'),
    # url(r'^openshift/', include('openshift.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^adminzone/', include(admin.site.urls)),
    url(r'^', include('administration.urls', namespace="administration")), #here go /administration beside r'^'
    # url(r'^payments/', include('payment.standard.ipn.urls')),
    # url(r'^captcha/', include('captcha.urls')),
    
    #url(r'^accounts/', include('userena.urls')),  

    #url(r'^accounts/', include('registration.backends.default.urls')),
)

wsgi/openshift/templates/templateNinjax/about.html
{% include "base.html" %}
<title>About us</title>
<!-- Cufon START  -->
<script type="text/javascript" src="{{ STATIC_URL }}js/cufon-yui.js"></script>
<script src="{{ STATIC_URL }}js/GeosansLight_500.font.js" type="text/javascript"></script>
<script type="text/javascript">
Cufon.replace('.logo', { fontFamily: 'GeosansLight' });
Cufon.replace('h1', { fontFamily: 'GeosansLight' });
Cufon.replace('h2', { fontFamily: 'GeosansLight' });
Cufon.replace('.pages_banner', { fontFamily: 'GeosansLight' });
</script>    
<!-- Cufon END  -->
</head>
<body>
<div id="main_container">        
	<div class="header">

            <a href="/"><div class="logo"></div></a>
            <div class="slogan">| solutions</div> 
        
			<div class="header_socials">
            <a href="#"><img src="{{ STATIC_URL }}images/rss.png" alt="" title="" border="0" /></a>
            <a href="#"><img src="{{ STATIC_URL }}images/facebook.png" alt="" title="" border="0" /></a>
            <a href="#"><img src="{{ STATIC_URL }}images/linkedin.png" alt="" title="" border="0" /></a>
            <a href="#"><img src="{{ STATIC_URL }}images/twitter.png" alt="" title="" border="0" /></a>
            <a href="#"><img src="{{ STATIC_URL }}images/flickr.png" alt="" title="" border="0" /></a>
            </div>

    </div> <!--end of header--> 
    
    <div class="menu">
        <ul>
        <li><a href="/">Home</a></li>
        <li><a href="#">Services<!--[if IE 7]><!--></a><!--<![endif]-->
        <!--[if lte IE 6]><table><tr><td><![endif]-->
            <ul>
            <li><a href="" title="">Webdesign</a></li>
            <li><a href="" title="">Programming</a></li>
            <li><a href="" title="">Development</a></li>
            <li><a href="" title="">Coding</a></li>
            </ul>
        <!--[if lte IE 6]></td></tr></table></a><![endif]-->
        </li>
        <li><a href="">Portfolio</a></li>
        <!--<li><a href="">Testimonials</a></li>-->
        <li><a href="/about">About Us<!--[if IE 7]><!--></a><!--<![endif]-->
        <!--[if lte IE 6]><table><tr><td><![endif]-->
            <ul>
            <li><a href="/about" title="">Out Team</a></li>
            <li><a href="/about" title="">Departments</a></li>
            <li><a href="/about" title="">Locations</a></li>
            </ul>
        <!--[if lte IE 6]></td></tr></table></a><![endif]-->
        </li>
        
        <li><a href="/blog/{{ dataBlog.id }}/">Blog</a></li>
        <li><a href="/contact">Contact</a></li>
        <li><a href="/development">Development</a></li>
        </ul>
    </div>
         
         
         
		<div class="center_content_pages">
        	<div class="pages_banner">

                <div id="nameBanner">
                        More details about us
                </div>    
                {% if name %}
                <div id="loguer">
                    Hola {{ name }}! <button id="logOutButton" value="/logout/about"  >Salir</button>
                </div> 
                {% endif %}

            </div>
        	<div class="left_content"> 
                       
                <div class="box290">
                <h2>Subpages</h2>
                    <ul class="left_menu">
                        <li><a href="about.html" title="">Out Team</a></li>
                        <li><a href="about.html" title="">Departments</a></li>
                        <li><a href="about.html" title="">Locations</a></li>
                    </ul>
                </div>
                
                <div class="box290">
                  <h2>From the Blog</h2>
                    <div class="news_box">
                        <div class="date">15.10.2011</div>
                        <h3><a href="#">Lore ipsum doloer ametis</a></h3>
                        <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                        </p>
                    </div>
                    <div class="news_box">
                        <div class="date">08.10.2011</div>
                        <h3><a href="#">Lore ipsum doloer ametis</a></h3>
                        <p>
                        Lorem ipsum dolor sit amet, consectetur adipisicing elit 
                        </p>
                    </div>               
                </div>
            </div> <!--end of left content-->
            
            
            <div class="right_content">
              <h2>Sed do eiusmod tempor incididunt ut</h2>
              		<img src="{{ STATIC_URL }}images/pages.jpg" alt="" title="" border="0" class="pages_pic" />
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                    <br /><br />
                    Sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                    </p>
                    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. 
                    sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                    </p>
            </div>
            
            
            
        <div class="clear"></div>
        </div>  
         
        
        
        
<div class="footer">
    <div class="copyrights">
    Free CSS Template by <a href="http://csstemplatesmarket.com" target="_blank">Css templates market</a>
    </div>
    <div class="footer_right">
    <a href="#">Home</a>
    <a href="#">About Us</a>
    <a href="#">Privacy Policy</a>
    <a href="#">Contact Us</a>
    </div>
    <div class="clear"></div>
</div>

</div> <!--end of main container-->
    
    

</body>
</html>

wsgi/openshift/templates/templateNinjax/blog.html
{% include "base.html" %}
<!-- Cufon START  -->
<script type="text/javascript" src="{{ STATIC_URL }}js/cufon-yui.js"></script>
<script src="{{ STATIC_URL }}js/GeosansLight_500.font.js" type="text/javascript"></script>
<script type="text/javascript">
Cufon.replace('.logo', { fontFamily: 'GeosansLight' });
Cufon.replace('h1', { fontFamily: 'GeosansLight' });
Cufon.replace('h2', { fontFamily: 'GeosansLight' });
Cufon.replace('.pages_banner', { fontFamily: 'GeosansLight' });
</script>    
<!-- Cufon END  -->
</head>
<body>
<div id="main_container">

        
	<div class="header">

            <a href="/"><div class="logo"></div></a>
            <div class="slogan">| solutions</div> 
        
			<div class="header_socials">
            <a href="#"><img src="{{ STATIC_URL }}images/rss.png" alt="" title="" border="0" /></a>
            <a href="#"><img src="{{ STATIC_URL }}images/facebook.png" alt="" title="" border="0" /></a>
            <a href="#"><img src="{{ STATIC_URL }}images/linkedin.png" alt="" title="" border="0" /></a>
            <a href="#"><img src="{{ STATIC_URL }}images/twitter.png" alt="" title="" border="0" /></a>
            <a href="#"><img src="{{ STATIC_URL }}images/flickr.png" alt="" title="" border="0" /></a>
            </div>

    </div> <!--end of header--> 
    
    <div class="menu">
        <ul>
        <li><a href="{% url 'index' %}">Home</a></li> <!-- other way to call one page, this form is with url name-->
        <li><a href="#">Services<!--[if IE 7]><!--></a><!--<![endif]-->
        <!--[if lte IE 6]><table><tr><td><![endif]-->
            <ul>
            <li><a href="" title="">Webdesign</a></li>
            <li><a href="" title="">Programming</a></li>
            <!--<li><a href="" title="">Development</a></li>-->
            <li><a href="" title="">Coding</a></li>
            </ul>
        <!--[if lte IE 6]></td></tr></table></a><![endif]-->
        </li>
        <li><a href="">Portfolio</a></li>
        <!--<li><a href="">Testimonials</a></li>-->
        <li><a href="/about">About Us<!--[if IE 7]><!--></a><!--<![endif]-->
        <!--[if lte IE 6]><table><tr><td><![endif]-->
            <ul>
            <li><a href="/about" title="">Out Team</a></li>
            <li><a href="/about" title="">Departments</a></li>
            <li><a href="/about" title="">Locations</a></li>
            </ul>
        <!--[if lte IE 6]></td></tr></table></a><![endif]-->
        </li>
        
        <li><a href="/blog/{{ dataBlog.id }}/">Blog</a></li>
        <li><a href="/contact">Contact</a></li>
        <li><a href="/development">Development</a></li>
        </ul>
    </div>
         
    <!-- <li><a href="{% url 'index' %}">Home</a></li>-->
         
		<div class="center_content_pages">
        	<div class="pages_banner">
        
                <div id="nameBanner">
                    Blog
                </div>    
                {% if name %}
                <div id="loguer">
                    Hola {{ name }}! <button id="logOutButton" value="/logout/blog/{{ datablog.id }}" >Salir</button>
                </div> 
                {% endif %}

            </div>

        	<div class="left_content"> 

                <div class="box290">
                  <h2>From the Blog</h2>
                  {% for data in dataBlog4 %}
                    <div class="news_box">
                        <div class="date">{{ data.pub_date|date:"F j, Y" }}</div>
                        <h3>
                            <a href="{% url 'blog' data.id %}">{{ data.title }}</a>
                        </h3> <!--calling url and redirectioning to blog with that name and parameter data.id -->
                        <p>
                        {{ data.content|truncatewords:22|safe}}
                        </p>
                    </div>
                  {% endfor %}   
                                
                </div>
            </div> <!--end of left content-->
            
            
            <div class="right_content">
              <h2>{{ dataBlogChoose.title }}</h2>
              		<img id="imageBlog" src="{{ dataBlogChoose.urlImage }}" alt="" title="" border="0" class="pages_pic" />
                    <p>
                        {{ dataBlogChoose.content|safe }}
                    </p>
            </div>
            
            
            
        <div class="clear"></div>
        </div>  
         
        
        
        
<div class="footer">
    <div class="copyrights">
    NinjaSolutions - 2013(c) All rights reserved 
    </div>
    <div class="footer_right">
    <a href="/">Home</a>
    <a href="/about">About Us</a>
    <a href="#">Privacy Policy</a>
    <a href="/contact">Contact Us</a>
    </div>
    <div class="clear"></div>
</div>

</div> <!--end of main container-->
    
    

</body>
</html>

wsgi/openshift/templates/templateNinjax/buttonsLoginRegister.html
<iframe id="dialog-modal"  title="Crear un nuevo usuario en Ninjax" src="/register/{{ myPlace }}" >
  <p>Your browser does not support iframes.</p>
</iframe>
<iframe id="dialog-modal-login"  title="Logueate en  Ninjax" src="/login/{{ myPlace }}" >
  <p>Your browser does not support iframes.</p>
</iframe>            

<button id="create-user" >Crea un nuevo usuario</button>
<button id="buttonLoguin" >Logueate</button>

wsgi/openshift/templates/templateNinjax/changepassword.html
{% extends "base.html" %}

{% block content %}
<style type="text/css">
.form-medium .control-label {
    width: 180px;
}
.form-medium .controls {
    margin-left: 200px;
}
</style>
<h2><i class="icon-key"></i> Cambiar mi contraseña</h2>
<p class="big grey">Crear una nueva contraseña para mi cuenta.</p>

<hr />


<div class="row">
	<div class="span8">
		<div class="well">
			<form  class="form-horizontal form-medium" method="post" name="form_newpassword"> {% csrf_token %} <!--if don't existe action reload in the same page-->
				{{ form.username }}
				{% if form.non_field_errors %}
				<div class="alert alert-block"> 
					{{ form.non_field_errors }}
				</div>
				{% endif %}
				<label class="control-label">Antigua Contraseña</label>
				{% if form.old_password.errors %}
				<div class="control-group error">
				{% else %}
				<div class="control-group">
				{% endif %}
					<div class="controls">{{ form.old_password }}</div>
				</div>
			
				<label class="control-label">Nueva Contraseña</label>
				{% if form.new_password.errors %}
				<div class="control-group error">
				{% else %}
				<div class="control-group">
				{% endif %}
					<div class="controls">{{ form.new_password }}</div>
				</div>
			
				<label class="control-label">Reescribe Nueva Contraseña</label>
				{% if form.retype_new_password.errors %}
				<div class="control-group error">
				{% else %}
				<div class="control-group">
				{% endif %}
					<div class="controls">{{ form.retype_new_password }}</div>
				</div>
				<div class="form-actions">
					<button type="submit" class="btn btn-primary">Continuar</button>
				</div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

wsgi/openshift/templates/templateNinjax/conditions.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

{% block content %}

<style type="text/css">
	.center {
		float: none;
		margin-left: auto;
		margin-right: auto;
	}
</style>

<div class="row center">
	<div class="span12">
		
        <div class="well c-soon">
            <!-- <p class="soon-med">We are on the way...</p>     -->
            <h3 id="myModalLabel">Términos y Condiciones</h3>                    
            <p>Ninjax Solutions protege tu compra de PerfectAimbot, dándole seguridad en:</p>
			<ol>
				<li>En caso de que el bot deje de funcionar por causas de nuestro servidor o alguna actualización de dragonbound, estos días se le repondrán(aumentaran) a su tiempo de compra.</li>
				<li>En caso deje de funcionar PerfectAimbot permanentemente, se le repondrá su pago en relación a los días restantes en otra aplicación o dinero.</li>
				<li>Sus cuentas de NinjaxSolutions y compras son protegidas, pero no nos responsabilizamos si ustedes entrega esos datos a otras personas y estos modifican sus contraseñas.</li>
				<li>Las cuentas Free solo funcionan una única vez con una determinada cuenta de dragonbound y ya no podrá ser usado en otra cuenta Free a futuro.</li>
				<li>Las cuentas Premium son mas seguras, y tienen soporte a cualquier necesidad vía ninjaxcompany@gmail.com</li>
			</ol>
                       
        </div>

    </div>
	
</div>
{% endblock %}

wsgi/openshift/templates/templateNinjax/detail.html
<html>

<h1>{{ poll.question }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url vote poll.id %}" method="post">
{% csrf_token %}
{% for choice in poll.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>
</html>

wsgi/openshift/templates/templateNinjax/development.html
{% extends "base.html" %}

{% block title %}{{ title }}{% endblock %}

<!-- {% block place %}{{ myPlace }}{% endblock %} -->

{% block content %}

<!-- Image blocks starts -->
<a name="beginBots"></a>
<h2>Categorías</h2>
<div class="row">
			<div class="span12">
				<div class="bor"></div>
				<ul class="hover-block">
					<li>
						<a href="{% url 'administration:bots' %}#beginBots">
							<!-- Image -->
							<img src="{{ STATIC_URL }}img/photos/Bot.jpg" alt="" /> 
							<!-- Content with background color Class -->
							<div class="hover-content b-blue">
								<h6>Bots</h6>
								Procesos automáticos para tus servicios preferidos
							</div>
						</a>
					</li>
					<li>
						<a href="#">
							<img src="{{ STATIC_URL }}img/photos/apps.png" alt="" /> 
							<div class="hover-content b-green">
								<h6>Aplicaciones Móviles</h6>
								Aplicaciones simples, para un uso diario.
							</div>
						</a>
					</li>					
				</ul>
				<div class="clearfix"></div>
			</div>
		</div>
<!-- Image blocks ends -->
	<hr/>
	
	<div class="row">

		<div class="span12"> 
			 <h2>
					<a href="{% url 'administration:bots' %}">  {{ category }}</a> 
					{% block hierarchySpecific %} {% endblock %}
			 </h2>  <!-- to make hierarchy-->
			 <hr/>
		</div>

	</div>

	<a name="beginSpecifBot"></a> 
	{% block contentBots %} {% endblock %} <!--called by bots.html-->
	{% block contentSpecificBots %} {% endblock %}

	
{% endblock %}

wsgi/openshift/templates/templateNinjax/frameToDownAndPay.html
<!--(S) - (BAR)PART OF BOTTONS TO DOWNLOAD AND PAY !!!--> 
	<div class="row"> 
		<div class="span6" style="cursor: pointer" > <!-- data-toggle="modal" data-target="#alertDownloads"> -->
			 <a href="javascript:urlDowload();" 
				style="text-decoration: none">	<!-- to asegurate a gooddownload and putin comment when bot is broken -->
				<div class="well">
					<p><h2 class="letra"><i class="icon-download-alt"></i>Descargar</h2>Version 2.5 (18 mb)
				</div>
			</a> 
		</div>

		{% if user.is_authenticated %}

		<!--(S)by the moment-->
		<div id="btn-buy" class="span6" style="cursor: pointer" data-toggle="modal" data-target="#payModal" > 
			<!-- <a href="#" style="text-decoration: none"> -->		
			<div class="well" >
				<h2 class="letra"><i class="icon-money"></i> Comprar <img src="{{ STATIC_URL }}img/cards.png"></h2>
				S/. 15.00 ó $ 3.99 x 1 mes
			</div>
			<!-- </a > -->
		</div>
			
		{% else %}
		<div class="span6" style="cursor: pointer" data-toggle="modal" data-target="#myModal">
			<!-- <a href="#" style="text-decoration: none"> -->
			<div class="well" >
				<h2 class="letra"><i class="icon-money"></i> Comprar</h2>S/. 15.00 ó $ 3.99 x 1 mes
			</div>
			<!-- </a > -->
		</div>	
		
		{% endif %}
	</div>
<!--(E) - (BAR)PART OF BOTTONS TO DOWNLOAD AND PAY !!!--> 

wsgi/openshift/templates/templateNinjax/login.html
{% extends "base.html" %}

{% block title %}Iniciar Sesión{% endblock %}

{% block content %}

<div class="register">
	<div class="row">
		<div class="span4">
			<h2>Hola</h2>
			<p class="big grey">Tenemos varias promociones para ti.</p>
			<p>¿No tienes una cuenta? <a href="{% url 'administration:signup' %}">Regístrate ahora.</a></p>
		</div>
		<div class="span8">
			<div class="formy">
				<h5>Iniciar sesión</h5>
				<div class="form">
					<form  class="form-horizontal" method="post" name="formRegister"> {% csrf_token %} <!--if don't existe action reload in the same page-->
						{% if form.non_field_errors %}
						<div class="alert alert-block"> 
							{{ form.non_field_errors }}
						</div>

						{% endif %}
						<label class="control-label">Email</label>
						{% if form.email.errors %}
						<div class="control-group error">
						{% else %}
						<div class="control-group">
						{% endif %}
							<div class="controls">{{ form.email }}</div>
						</div>
						<label class="control-label">Contraseña</label>
						{% if form.password.errors %}
						<div class="control-group error">
						{% else %}
						<div class="control-group">
						{% endif %}
							<div class="controls">{{ form.password }}</div>
						</div>
						<div class="form-actions">
							<button type="submit" class="btn btn-success">Iniciar Sesión</button>
							<button type="reset" class="btn btn-primary">Limpiar</button>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
{% endblock %}

wsgi/openshift/templates/templateNinjax/results.html
<h1>{{ poll.question }}</h1>

<ul>
{% for choice in poll.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url detail poll.id %}">Vote again?</a>

wsgi/openshift/templates/templateNinjax/signin.html
<!doctype html>
<html lang="en">
<head>
	<meta charset="UTF-8">
	<title>Document</title>
</head>
<body>
	<form  id="formLogin" method="post" name="formRegister"> {% csrf_token %} <!--if don't existe action reload in the same page-->
		{{ form.non_field_errors }}              
		<div class="form_row"> 
			<label>Emaill</label>   
			{{ form.email }}
			{{ form.email.errors }}
		</div>   
		<div class="form_row"> 
			<label>Contraseña</label>                   
			{{ form.password }}
			{{ form.password.errors }}
		</div>  
	  <p><input type="submit" id="logued" class="form_submit" value="Logueate" /></p>
	</form>
</body>
</html>

wsgi/openshift/templates/templateNinjax/signup.html
{% extends "base.html" %}

{% block title %}Registrate{% endblock %}

{% block content %}
<script type="text/javascript">
	 $(function(){ 
	 	$("#notCopyAndPaste").bind("paste",function(e) {  
                     e.preventDefault();  
                }); 
	 });

</script>
<div class="register">
	<div class="row">
		<div class="span4">
			<h2>Registráte Hoy</h2>
			<p class="big grey">Tenemos varias promociones para ti.</p>
			<p>Prometemos no spamearte :) </p>
			<p>¿Ya tienes una cuenta? <a href="{% url 'administration:login' %}">Iniciar sesión</a></p>
		</div>
		<div class="span8">
			<div class="formy">
				<h5>Registro</h5>
				<div class="form">
					<form class="form-horizontal" method="post"> {% csrf_token %}
						{% if form.non_field_errors %}
						<span class="tidate b-red">
							{{ form.non_field_errors }}
						</span>
						<br>
						{% endif %}
						<div class="control-group"> 
							<label class="control-label">Email</label>
							<div class="controls">{{ form.email }}</div>
							{% if form.email.errors %}
							<span class="tidate b-red">{{ form.email.errors }}</span>
							{% endif %}
						</div>
						<div class="control-group"> 
							<label class="control-label">Confirmar Email</label>
							<div class="controls" id="notCopyAndPaste" >{{ form.emailConfirm }}</div>
							{% if form.email.errors %}
							<span class="tidate b-red">{{ form.emailConfirm.errors }}</span>
							{% endif %}
						</div>
						<div class="control-group"> 
							<div class="controls">{{ form.captcha }}</div>
							<!-- {% if form.email.errors %} -->
							<span >{{ form.captcha.errors }}</span>
							<!-- {% endif %} -->
						</div>
						<div class="tidate b-purple"> 
						    <!-- Un correo con la CONTRASEÑA de tu cuenta sera enviado a tu email, tu USUARIO sera tu mismo email. -->
						    <!-- <p>Your PASSWORD will be sent to your email.</p> -->
						    <p>Tu CONTRASEÑA será enviada a tu correo electrónico.</p>
				        </div>

						<div class="form-actions">
							<button type="submit" class="btn btn-success">Registrar</button>
							<button type="reset" class="btn btn-primary">Limpiar</button>
						</div>
					</form>
					
				</div>
			</div>
		</div>
	</div>
</div>


{% endblock %}

wsgi/openshift/templates/templateNinjax/thanks.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %} 
{% load epoch %}
{% block content %}
<div class="row">
	<div class="span12">
		<div class="well c-soon">
			<p class="soon-big"><i class="icon-thumbs-up"></i></p>
			<p class="soon-big">¡Gracias!</p>
			<p class="soon-med">Tu registro se ha realizado con éxito.</p>
			<p class="soon-small">Un email ha sido enviado con tu contraseña.</p>
			<p class="soon-med"><a href="{% url 'administration:login' %}">Ingresa con tu cuenta ahora.</a></p>
		</div>
	</div>
</div>
{% endblock %} 

wsgi/openshift/templates/templateNinjax/userprofile.html
{% extends "base.html" %}

{% block title %}Profile{% endblock %} 
{% load epoch %}
{% block content %}

{% if purchases %}

	<h5>Usuario: {{suser.email}}</h5> <br />
	<h6> Total: {{ purchases|length }} <em>Compras</em> <br /> </h6>
	<table class="table table-striped table-hover table-bordered">
		<thead>
			<tr>
				<th center width="20%">Nombre de la App</th>
				<th center width="20%">Tipo de Compra</th>
				<th width="25%">Comprada el </th>
				<th width="20%">Tiempo de licencia</th>
				<th width="15%">Cuentas</th>
			</tr>
		</thead>
		<tbody>
				{% for purchase in purchases %}
				<tr>
					<td>{{purchase.5}}</td>
					{% if purchase.0 == 1%}
					<td>Premium</td>
					{% else %}
					<td>Free</td>
					{% endif %}
					<td>{{purchase.1|fromunix|date:"jS F Y"  }}</td>
					<td>{{purchase.2|time_in_days}}</td>
					<td>{{purchase.4}} / {% if purchase.0 == 1 %} 5 {% elif purchase.0 == 0 %} 1 {% else %} 3{% endif %}</td>
				</tr>
				{% endfor %}
		</tbody>
	</table>
<a href="{% url 'administration:activatepremium' %}" role="button" class="btn btn-primary">Activar Premium</a>
{% else %}
	<div class="well"><h6>El usuario no ha realizado ninunga compra</h6>
{% endif %}
<hr /

{% endblock %}