wsgi/openshift/administration/urls.py
from django.conf.urls import patterns, url
from administration import views
from django.contrib.auth.decorators import login_required, user_passes_test

urlpatterns = patterns('',
	url(r'^$', views.index, name='index'),
	url(r'^contact/', views.contact, name='contact'), 
	url(r'^about/', views.about, name='about'),    
	url(r'^blog/(?P<blog_id>\d+)/$', views.blog, name='blog'),
	url(r'^signup/$', views.signup, name='signup'),
	url(r'^login/$', views.login_user, name='login'),
	# url(r'^login/(?P<same_site>\w+)/$', views.login_user, name='login'),
	url(r'^profile/$', login_required(views.profile), name='profile'),
	url(r'^profile/changepassword/$', login_required(views.change_password), name='changepassword'),
	url(r'^asdjsaidio21u312/sendemail/$', login_required(views.sendEmailAimbot), name='sendemailaimbot'),
	url(r'^adlsakd9012312123/activatepremium/$', login_required(views.activatePremium), name='activatepremium'),
	url(r'^ddj9pqjdwq09dj90ad/showuserprofile/(?P<pk>\d+)/$', login_required(views.showUserProfile), name='showuserprofile'),
	url(r'^asdasdj90je9032je903je932je029ej2903je9032je9032e/premiums/$', login_required(views.PremiumListJSON.as_view()), name='premiums'),
	url(r'^cnaisncoasdaoisdjddj9j0021312dapajdznmnzadi0123jd/payments/$', login_required(views.PaymentListJSON.as_view()), name='payments'),
	url(r'^logout/$', views.logout_user, name='logout'),
	# url(r'^setusername/(?P<user_url>\w+)/$', views.setUsername, name='setUsername'),
	url(r'^development/$', views.development, name='development'),
	url(r'^development/sendvoucher/$', views.sendVoucher, name='sendvoucher'),
	# url(r'^development/payment/$', views.view_that_asks_for_money, name='payment'),
	url(r'^development/bots/$', views.bots, name='bots'),
	url(r'^development/events/$', views.events, name='events'),	
	url(r'^development/confirmpurchase/$', login_required(views.confirm_purchase), name='confirm_purchase'),	
	# url(r'^development/no_authorized/$', views.confirm_purchase, name='confirmpurchase'),
	url(r'^development/bots/(?P<bot>\w+)/$', views.specificBot, name='specificBot'),
	url(r'^conditions/$', views.conditions, name='conditions'),
)

wsgi/openshift/urls.py
from django.conf.urls.defaults import patterns, include, url

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

handler404 = 'mysite.views.handler404'


urlpatterns = patterns('',
    # Examples:
    #url(r'^$', 'openshift.views.home', name='home'),
    # url(r'^openshift/', include('openshift.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^adminzone/', include(admin.site.urls)),
    url(r'^', include('administration.urls', namespace="administration")), #here go /administration beside r'^'
    # url(r'^payments/', include('payment.standard.ipn.urls')),
    # url(r'^captcha/', include('captcha.urls')),
    
    #url(r'^accounts/', include('userena.urls')),  

    #url(r'^accounts/', include('registration.backends.default.urls')),
)

wsgi/openshift/templates/base.html
 <!DOCTYPE html>
<html lang="en">
<head>
	<meta charset="utf-8" />
	<title>{% block title %} {% endblock %}</title>
	<meta name="viewport" content="width=device-width, initial-scale=1.0" />
	<meta name="description" content="" />
	<meta name="keywords" content="" />
	<meta name="author" content="" />
	<!-- Stylesheets -->
	<link href="{{ STATIC_URL }}style/bootstrap.css" rel="stylesheet" />
	<link rel="stylesheet" href="{{ STATIC_URL }}style/font-awesome.css" />
	<link href="{{ STATIC_URL }}style/prettyPhoto.css" rel="stylesheet" />
	<!-- Parallax slider -->
	<link rel="stylesheet" href="{{ STATIC_URL }}style/slider.css" />
	<!-- Flexslider -->
	<link rel="stylesheet" href="{{ STATIC_URL }}style/flexslider.css" />

	<link href="{{ STATIC_URL }}style/style.css" rel="stylesheet" />

	<!-- Colors - Orange, Purple, Light Blue (lblue), Red, Green and Blue -->
	<link href="{{ STATIC_URL }}style/blue.css" rel="stylesheet" />

	<link href="{{ STATIC_URL }}style/bootstrap-responsive.css" rel="stylesheet" />
	<link href="{{ STATIC_URL }}style/ninjax.css" rel="stylesheet" />
	<link href="{{ STATIC_URL }}style/datepicker.css" rel="stylesheet" />
	
	<!-- HTML5 Support for IE -->
	<!--[if lt IE 9]>
	<script src="{{ STATIC_URL }}js/html5shim.js"></script>
	<![endif]-->

	<!-- Favicon -->

	<link rel="shortcut icon" href="{{ STATIC_URL }}img/favicon.ico" />
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" /></head>

<body >

	</style>
	<!-- JS -->
<script src="{{ STATIC_URL }}js/jquery-1.10.2.min.js"></script>
<script src="{{ STATIC_URL }}js/jquery.dataTables.js"></script>
<script src="{{ STATIC_URL }}js/jquery.dataTables.bootstrap.js"></script>
<script src="{{ STATIC_URL }}js/bootstrap.js"></script> 
<script src="{{ STATIC_URL }}js/jquery.isotope.js"></script> <!-- Isotope for gallery -->
<script src="{{ STATIC_URL }}js/jquery.prettyPhoto.js"></script> <!-- prettyPhoto for images -->
<script src="{{ STATIC_URL }}js/jquery.cslider.js"></script> <!-- Parallax slider -->
<script src="{{ STATIC_URL }}js/modernizr.custom.28468.js"></script>
<script src="{{ STATIC_URL }}js/filter.js"></script> <!-- Filter for support page -->
<script src="{{ STATIC_URL }}js/cycle.js"></script> <!-- Cycle slider -->
<script src="{{ STATIC_URL }}js/jquery.flexslider-min.js"></script> <!-- Flex slider -->
<script src="{{ STATIC_URL }}js/bootstrap-datepicker.js"></script> 

<script src="{{ STATIC_URL }}js/easing.js"></script> <!-- Easing -->
<script src="{{ STATIC_URL }}js/custom.js"></script>
<script src="{{ STATIC_URL }}js/ninjax2.js"></script>
<script type="text/javascript">
	
</script>
<!-- <script type="text/javascript" src="https://www.java.com/js/deployJava.js"></script> -->
	<style type="text/css">
	.login{
		float: right;
	}
	.navbar .nav > li > a{
		color: #FFF;
	}
	</style>
	<!-- Header Starts -->
	<header>
		<div class="container">
			<div class="row">
				<div class="span6">
					<div class="logo">
						<h1><a href="/"><img src="{{ STATIC_URL }}images/logo3.png"> </a></h1>
					</div>
				</div>
				<div class="span6">
					<div class="row">
						
					</div>
				</div>
			</div>
		</div>
	</header>
	<div class="navbar">
	 <div class="navbar-inner">
		 <div class="container">
			 <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
				 <span>Menu</span>
			 </a>
			 <div class="nav-collapse collapse" >
				 <ul class="nav" >
					<li ><a class="menuHome" href="/">Inicio</a></li>
				 </ul>
			 </div>
			 {% if menuState == "Home" %}
			 	<script type="text/javascript">
			 		$(function()
		 			{
		 				$(".menuHome").css(
		 					{"backgroundColor":"rgb(243, 243, 243)","color":"rgb(255, 255,255)"}
		 					);		 						 				
		 			});
			 	</script>
			 {% endif %}

			 <div class="nav-collapse collapse">
				 <ul class="nav">
					 <li>
					 	<a  class="menuDevelopment" href="{% url 'administration:development' %}">
					 		Desarrollo
					 	</a>
					 </li>
				 </ul>
			 </div>
			 {% if menuState == "Development" %}
			 	<script type="text/javascript">
			 		$(function()
		 			{
		 				$(".menuDevelopment").css(
		 					{"backgroundColor":"rgb(243, 243, 243)","color":"rgb(255, 255,255)"}
		 					);
		 				$(".navbar .nav > li > a:visited").css(
		 					{"color":"rgb(243, 243, 243)"}
		 					);
		 			});
			 	</script>
			 {% endif %}

			 <div class="nav-collapse collapse">
				 <ul class="nav">
					 <li><a href="#">Blog</a></li>
				 </ul>
			 </div>
			 {% if menuState == "Blog" %}
			 	<script type="text/javascript">
			 		$(function()
		 			{
		 				$(".menuDevelopment").css({"backgroundColor":"#E66D1C"});
		 				// console.log("entra aqui");
		 			});
			 	</script>
			 {% endif %}

			 <div class="nav-collapse collapse">
				 <ul class="nav">
					 <li><a href="#">Contacto</a></li>
				 </ul>
			 </div>
			 {% if menuState == "Contact" %}
			 	<script type="text/javascript">
			 		$(function()
		 			{
		 				$(".menuDevelopment").css({"backgroundColor":"#E66D1C"});
		 				// console.log("entra aqui");
		 			});
			 	</script>
			 {% endif %}

			 <div class="nav-collapse collapse">
				 <ul class="nav">
					 <li><a href="#">Nosotros</a></li>
				 </ul>
			 </div>
			 {% if menuState == "About" %}
			 	<script type="text/javascript">
			 		$(function()
		 			{
		 				$(".menuDevelopment").css({"backgroundColor":"#E66D1C"});
		 				// console.log("entra aqui");
		 			});
			 	</script>
			 {% endif %}

			 {% if not user.is_authenticated %}
			 <div class="nav-collapse collapse login">
			 	
				 <ul class="nav">
				 	 <!-- <input type="hidden" name="next" value="{{ myPlace }}" /> -->
					 <li><a href="{% url 'administration:login' %}">Iniciar Sesión</a></li>
				 </ul>
			 </div>
			 <div class="nav-collapse collapse login">
				 <ul class="nav">
					 <!-- <li><a href="#" data-toggle="modal" data-target="#myModal" >Registro</a></li> -->
					 <li><a href="{% url 'administration:signup' %}" >Registrate</a></li>
				 </ul>
			 </div>
			 {% else %}			 
			 <div class="nav-collapse collapse login">
				 <ul class="nav">
					<li class="dropdown"><a href="#" class="dropdown-toggle" data-toggle="dropdown"> {{ user }}<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="{% url 'administration:profile' %}">Mi Perfil</a></li>
							<li><a href="{% url 'administration:logout' %}">Salir</a></li>
						</ul>
					</li>
				 </ul>
			 </div>
			 {% endif %}
			</div>

			 <!--(S)-modal-->
				<!-- <div id="myModal" class="modal hide fade" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-hidden="true">×</button>
						<h3 id="myModalLabel">AVISO : </h3>
					</div>
					<div class="modal-body">
						<div class="span6">

								<a href="{% url 'administration:events' %}" style="text-decoration: none">
					        <div class="" style="cursor: pointer">
					          <div class="service">
					            <div class="b-red serv-block" style="cursor: pointer">
					              <i class="icon-warning-sign"></i>
					              <h3>Solo Registrarse desde PROMOCION. </p>
					              </h3>
					            </div>
					            		Guiate del video: 
					              	<p><a class="b-green serv-block" target="_blank" href="http://www.youtube.com/watch?v=Pc1tbOKshEc">http://www.youtube.com/watch?v=Pc1tbOKshEc</a>
					            <p>El registro normal estara descativado hasta terminar el tiempo de las 100 cuentas
					            	PREMIUM obsequiadas.</p>
					            
					          </div>
					        </div>
				        </a>

				        
				      </div>
				      <div class="clearfix"></div>
							 
					</div>
					
				</div> -->
			<!--(E)modal-->
	 </div>
 	</div>
	<div class="content">
		<div class="container">				
			{% block content %} {% endblock %}
			
		</div>
	</div>

<!-- Social start-->

<div class="social-links">
  <div class="container">
    <div class="row">
      <div class="span12">
        <p class="big"><span>Síguenos en</span> 
        	<a href="https://www.facebook.com/ninjaxsolutions" target="_blank">
        		<i class="icon-facebook"></i>Facebook</a> 
        	<a href="https://twitter.com/Ninjaxsolutions" target="_blank">
        		<i class="icon-twitter"></i>Twitter</a> 
        	<a href="https://plus.google.com/u/2/112503482328632680538" target="_blank">
        		<i class="icon-google-plus" ></i>Google Plus</a>
        	<!-- <a href="#"><i class="icon-linkedin" target="_blank"></i>LinkedIn</a></p> -->
      </div>
    </div>    
  </div>
</div>

<!-- Social ends-->
		<!-- Footer -->
<footer>
  <div class="container">
    <div class="row">
      <div class="span12">
          <div class="copy">
            <h6>Ninjax <span class="color">Solutions</span></h6>
            <p>Copyright &copy; <a href="#">Ninjax</a> - <a href="#">Inicio</a> | <a href="#">Acerca de</a> | <a href="#">FAQ</a> | <a href="#">Contáctanos</a></p>
          </div>
      </div>
    </div>
  <div class="clearfix"></div>
  </div>
</footer> 


</body>
</html>